### ISSUE TITLE
【内容优化】推荐更多的文档质量检查工具

### ISSUE THREAD

**Issue by yikeke** [yikeke/zh-style-guide#11]
目前的[“文档质量检查工具”一节](https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%8B%BC%E5%86%99%E4%B8%8E%E8%AF%AD%E6%B3%95/%E6%96%87%E6%A1%A3%E8%B4%A8%E9%87%8F%E6%A3%80%E6%9F%A5%E5%B7%A5%E5%85%B7.html)内容不够丰富详实，欢迎推荐更多的工具。

![image](https://user-images.githubusercontent.com/40977455/96805572-82d10480-1444-11eb-8782-ed52d41b2c9c.png)

**Comment by darkyzhou** [comment]
你好👋，我打算结合本仓库中的书写规则，给[textlint](https://github.com/textlint/textlint)贡献一些规则，这样我们就能利用textlint在各个编辑器上的插件让本仓库的规则得以被方便地套用，不知道这个想法怎么样呢🤔

**Comment by yikeke** [comment]
> 你好👋，我打算结合本仓库中的书写规则，给[textlint](https://github.com/textlint/textlint)贡献一些规则，这样我们就能利用textlint在各个编辑器上的插件让本仓库的规则得以被方便地套用，不知道这个想法怎么样呢🤔

当然是很棒的想法，如果有 lint 工具实现本指南，会是技术文档写作者/程序猿的福音！
