### ISSUE TITLE
【内容优化】选用阿拉伯数字和汉字数字均可——这个部分的原则不太清楚

### ISSUE THREAD

**Issue by shog86** [yikeke/zh-style-guide#13]
如题。

从下面的举例中，感觉很多例子其实都是用阿拉伯数字更好，三分之一这样的除外。

而且既然是技术文档，如果考虑到可能翻译到其他语言的需要，还是尽量使用阿拉伯数字，这样不仅清楚明白，更重要的是不会给翻译到其他语言形成障碍。

再者，像「100 多个数据中心」这样的，其实可能并不算「数字个数不多」。个人经验认为，五个以内可能才算「个数不多」。但如果考虑到第二点本地化的需求，可能除了「一」以及带数字的成语之外的其他数字都使用阿拉伯数字更稳妥些。

**Comment by oldLady344** [comment]
建议参考国标 GB/T15835—2011  4.3 部分的建议。

**Comment by yikeke** [comment]
目前 [选用阿拉伯数字和汉字数字均可](https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9%E5%85%83%E7%B4%A0/%E6%95%B0%E5%AD%97.html#id5) 一节正是参考国标 GB/T15835—2011 4.3 部分给出的建议。

对于 @shog86 在本地化场景下的考量，不无道理，但我有一点不同看法：英文中一般建议[“Numbers <10 are usually written as words; whereas numbers >9 are written in numerals”](https://procomm.ieee.org/using-numbers-in-technical-documents-2/)。站在这点考量的话，中文中小于十的数字用汉字表示无可厚非（当然，我并不知道其他语言的情况）。

由于此《风格指南》主要是站在如何写中文文档的视角来给出参考规范，如果特定公司/团队有本地化的需求，可以按需改动自己版本的相应规范即可。这里的母版要考虑普适性，所以先不改动了，谢谢各位的建议。
