### ISSUE TITLE
【内容优化】文档结构样式一文中对于如何规范使用标题的解释

### ISSUE THREAD

**Issue by yzeng25** [yikeke/zh-style-guide#19]
URL：https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%96%87%E6%A1%A3%E7%BB%93%E6%9E%84%E6%A0%B7%E5%BC%8F/%E7%9B%AE%E5%BD%95.html

问题描述：在“文档结构样式-目录”一文中，提到了“PingCAP 技术文档站的目录实现”，截图右侧的导航栏显示的是文档内部的标题层级（如1、2、3级）。在实际操作中，文档右侧导航栏能显示哪些层级，显示多少层级，由使用的文档框架决定。例如Rancher中文文档使用的是Docusaurus框架，虽然在正文中对标题级别没有限制，但是文档右侧导航栏只支持显示二级标题（##）和三级标题（###），一级标题（#）和四级（####）不会出现在右侧导航栏中。

修改建议：建议用户根据自己使用的文档框架自定义自己的标题层级，如果导航栏无法显示一级标题（#），则自己定义在本文中的一级标题为（##），二级标题为（###），以此类推。

**Comment by yikeke** [comment]
我在 [Rancher 中文文档](https://rancher.com/docs/rancher/v1.6/zh/quick-start-guide/)没有看到右侧导航栏，能帮忙提供个带右侧导航栏的 Rancher 文档链接吗 @yzeng25 

![image](https://user-images.githubusercontent.com/40977455/102957074-789ab780-4514-11eb-8a88-853c8bb7785d.png)

**Comment by yzeng25** [comment]
对， 你访问的旧版文档地址，那些文档我们已经不维护了。新版文档的地址和截图如下，谢谢！

URL: https://docs.rancher.cn/docs/rancher2/releases/v2.5.3/
截图：
![image](https://user-images.githubusercontent.com/36651058/102957288-ff4f9480-4514-11eb-964c-76dcb629a4af.png)

**Comment by yzeng25** [comment]
fixed https://github.com/yikeke/zh-style-guide/pull/20
