### ISSUE TITLE
【通俗易懂】在“通俗易懂.md”中的“各位 TW 们”不够通俗易懂

### ISSUE THREAD

**Issue by CroMarmot** [yikeke/zh-style-guide#27]
https://github.com/yikeke/zh-style-guide/blob/master/source/%E8%AF%AD%E8%A8%80%E9%A3%8E%E6%A0%BC/%E9%80%9A%E4%BF%97%E6%98%93%E6%87%82.md

![2021-02-24 16-50-28 的屏幕截图](https://user-images.githubusercontent.com/24691835/108974557-87424e00-76c0-11eb-83d3-618d4c4f3304.png)

**Comment by yikeke** [comment]
好，哈哈，不好意思是我疏忽了

**Comment by GeeLaw** [comment]
相关： https://www.v2ex.com/t/755812#r_10231300 和 https://twitter.com/geelaw95/status/1364470817413685255

建议：把 TW 改为”文档作者“，但《通俗易懂》这一篇的案例改成：

> ”欢迎各位 TW 们补充你身边的案例。“

即加上双引号表示这是刻意的例子。
