### ISSUE TITLE
【内容优化】列表的使用中的案例疑问

### ISSUE THREAD

**Issue by lycheng** [yikeke/zh-style-guide#33]
链接：https://github.com/yikeke/zh-style-guide/blob/master/source/%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9%E5%85%83%E7%B4%A0/%E5%88%97%E8%A1%A8.md#%E5%88%97%E8%A1%A8%E7%9A%84%E4%BD%BF%E7%94%A8

![image](https://user-images.githubusercontent.com/1016266/110090471-4c33cf00-7dd2-11eb-8352-d55224394a16.png)

这里感觉有点自相矛盾？但这两个规范我也觉得是合理的

**Comment by yikeke** [comment]
不矛盾，第 1 条规范中是指，如果可以变成统一的句子结构，比如「动词+名词」，那就尽量统一。

第一个红框内的动词有「支持」，也有「优化」。

如果第一个红框内的动词都用的「支持」，则可以像第二个红框的案例一样修改。

**Comment by lycheng** [comment]
OK
