### ISSUE TITLE
文中对英尺符号和英寸符号的使用是错误的

### ISSUE THREAD

**Issue by Geeyun-JY3** [yikeke/zh-style-guide#34]
无论是 GitHub 内源代码
https://github.com/yikeke/zh-style-guide/blob/9300c00325c5d508d15b11c8509b6bdc8d3f5558/source/%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9%E5%85%83%E7%B4%A0/%E5%8D%95%E4%BD%8D%E7%AC%A6%E5%8F%B7.md#L9

还是在线浏览网页：https://zh-style-guide.readthedocs.io/zh_CN/latest/%E6%96%87%E6%A1%A3%E5%86%85%E5%AE%B9%E5%85%83%E7%B4%A0/%E5%8D%95%E4%BD%8D%E7%AC%A6%E5%8F%B7.html#:~:text=%E4%B8%8D%E7%A9%BA%E6%A0%BC%E3%80%82%E5%A6%82%EF%BC%9A-,4%E2%80%995%E2%80%99%E2%80%99,-%E8%A1%A8%E7%A4%BA%204%20%E8%8B%B1%E5%B0%BA

对英尺符号和英寸符号的使用都是错误的。都没有使用角分符号和角秒符号，前者使用了垂直的 `'`（U+0027 Apostrophe）（且无使用斜体），后者使用了右单弯引号 `’`（U+2019 Right Single Quotation Mark）。[这篇文章](https://sspai.com/post/45516#:~:text=%E4%BD%86%E6%B3%A8%E6%84%8F%E4%B8%8D%E8%A6%81%E7%94%A8%E5%BC%AF%E5%BC%95%E5%8F%B7%EF%BC%8C%E5%9B%A0%E4%B8%BA%E8%A7%92%E5%88%86%E7%AC%A6%E5%8F%B7%E7%9A%84%E5%BD%A2%E6%80%81%E6%97%A0%E8%AE%BA%E5%A6%82%E4%BD%95%E4%B8%8D%E5%8F%AF%E8%83%BD%E6%98%AF%E5%BC%AF%E6%9B%B2%E7%9A%84%E3%80%82) 有谈及该符号的使用，可以参考一下。

**Comment by yikeke** [comment]
谢谢反馈，涨知识了👍 我参考你给的文章改了：
![image](https://user-images.githubusercontent.com/40977455/115348206-e9ad5b80-a1e4-11eb-8b62-1da96160867e.png)

**Comment by Geeyun-JY3** [comment]
不太建议附我上面给出的文章，我上面附的指向突出显示的内容的链接并没有作出详细解释和说明。
应该找更具权威的来源。

**Comment by yikeke** [comment]
再修改了下：
![image](https://user-images.githubusercontent.com/40977455/115353549-3a27b780-a1eb-11eb-9549-a37a975bce60.png)

**Comment by Geeyun-JY3** [comment]
嗯
