### ISSUE TITLE
国家标准局的《标点符号用法》

### ISSUE THREAD

**Issue by stfenjobs** [yikeke/zh-style-guide#38]
http://openstd.samr.gov.cn/bzgk/gb/newGbInfo?hcno=22EA6D162E4110E752259661E1A0D0A8 

不知道咱们社区 ，是否可借鉴、参考  

可否添加到 参考链接里

**Comment by yikeke** [comment]
好的，没问题

**Comment by yikeke** [comment]
![image](https://user-images.githubusercontent.com/40977455/134347566-65c56641-3051-4416-80c9-904dc09887cf.png)
原来没附链接，现在加上了
