### ISSUE TITLE
【错别字勘误】

### ISSUE THREAD

**Issue by SunACong** [yikeke/zh-style-guide#46]
<img width="1274" alt="微信图片_20231221104029" src="https://github.com/yikeke/zh-style-guide/assets/105342195/1618bf78-2037-4fc1-a3b5-c008b43b5250">

**Comment by liyannny** [comment]
信道复用和信道服用都有 我也分不清哪个正确？

**Comment by AnabasisXu** [comment]
`信道复用`更可取

**Comment by yikeke** [comment]
指南里有这个错别字吗？我没搜到

**Comment by mydevops** [comment]
这个页面来自于 javaguide.cn。
可以移步 https://github.com/Snailclimb/JavaGuide/issues 进行提交。
