### ISSUE TITLE
【前端问题】点击“显示源代码”后的 txt 文件出现中文乱码

### ISSUE THREAD

**Issue by yikeke** [yikeke/zh-style-guide#9]
如：https://zh-style-guide.readthedocs.io/zh_CN/latest/

点击“显示源代码”后：https://zh-style-guide.readthedocs.io/zh_CN/latest/_sources/index.rst.txt
![image](https://user-images.githubusercontent.com/40977455/96805254-c5dea800-1443-11eb-8811-18ea311cca2b.png)

**Comment by zhyantao** [comment]
或许，你可以[更改显示源代码为 ‘.rst’ 格式](https://www.sphinx-doc.org/en/master/usage/configuration.html?#confval-html_sourcelink_suffix)，但是这是[有风险的](https://github.com/sphinx-doc/sphinx/issues/88#issuecomment-68526053)。

**Comment by mydevops** [comment]
经过 Chrome 131.0.6778.86 版本测试该问题已经无法复现。

**Comment by mydevops** [comment]
问题原因，readthedocs 的设置问题。

需要将该项目的「语言:」修改为「Simplified Chinese」。

重新编译即可。
